### ISSUE TITLE
Program Structure

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/MoneyTaker#1]
# Basic Class Diagram For MoneyTaker

| class main| 
| ---------- |
| System MoneyTaker;
MoneyTaker.run();   |

| class System| 
| ---------- |
| MyUI mUI;
MyDBManager mDBM;
void run(){ while: mUI.mainScreen() };   |

| MyDBManager| 
| ---------- |
| TableList : unsettled value.
getQuarry(type , Tuple , tablename ) : str
insertTupleToTable(Tuple , tablename) : int
deleteTuplFromTable(Tuple , tablename) : int
updateTupleFromTable(Tuple , tablename): int |

**Comment by getCurrentThread** [comment]
# Basic Class Diagram For MoneyTaker



| class main| 
| ---------- |
| System MoneyTaker;
MoneyTaker.run();   |

| class System| 
| ---------- |
| MyUI mUI;
MyDBManager mDBM;
void run(){ while: mUI.mainScreen() };   |

| MyDBManager| 
| ---------- |
| TableList : unsettled value.
getQuarry(type , Tuple , tablename ) : str
insertTupleToTable(Tuple , tablename) : int
deleteTuplFromTable(Tuple , tablename) : int
updateTupleFromTable(Tuple , tablename): int |
|
| MyDBManager| 
| ---------- |

|
